; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-SuperMini]
platform = espressif32
; On garde une définition de board compatible et robuste
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem101

; --- Configuration Mémoire (Spécifique SuperMini S3) ---
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
board_build.filesystem = littlefs

; --- Drapeaux de compilation (Flash + USB + PSRAM) ---
build_flags = 
    -I include
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM

; --- Moniteur Série ---
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; --- Bibliothèques (Fusion de MPU6050 et FastLED) ---
lib_deps = 
    fastled/FastLED@^3.9.4
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit SSD1306@^2.5.13
    jrowberg/I2Cdevlib-MPU6050@^1.0.0